# Generated by Django 4.2.5 on 2023-12-11 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_autor', models.TextField(max_length=100)),
                ('apellidop_autor', models.TextField(max_length=15)),
                ('apellidom_autor', models.TextField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_editorial', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.TextField(max_length=10)),
                ('titulo_libros', models.TextField(max_length=100)),
                ('año_publicacion', models.TextField(max_length=4)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.categoria')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.editorial')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_usuario', models.TextField(max_length=15)),
                ('nombre_usuario', models.TextField(max_length=15)),
                ('apellidop_usuario', models.TextField(max_length=15)),
                ('apellidom_usuario', models.TextField(max_length=15)),
                ('correo_usuario', models.TextField(max_length=30)),
                ('telefono_usuario', models.TextField(max_length=15)),
                ('password_usuario', models.TextField(max_length=20)),
                ('direccion_usuario', models.TextField(max_length=30)),
                ('fecha_nacimiento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.TextField(max_length=10)),
                ('fecha_prestamo', models.DateTimeField()),
                ('fecha_devolucion', models.DateTimeField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libros')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_historial', models.TextField(max_length=200)),
                ('tabla_afectada_historial', models.TextField(max_length=100)),
                ('fecha_hora_historial', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.usuario')),
            ],
        ),
    ]
